name: Build POC

on:
  workflow_dispatch:
  push:
    branches:
      - '*'

jobs:
  build-test:
    name: Build & test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Build with maven
        run: mvn verify
